---

- name: Secure user creation
  hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: create users
      user:
        name: "{{ item.name }}"
        password: "{{ item.pwd | password_hash('sha512') }}"
        role: users
      loop: "{{ users }}"